using NRedberry.Solver;
using NRedberry.Tensors;
using NRedberry.Transformations.Symmetrization;
using TensorFactory = NRedberry.Tensors.Tensors;
using Xunit;

namespace NRedberry.Core.Tests.Solver;

public sealed class ExternalSolverTests
{
    [Fact]
    public void ShouldThrowArgumentNullExceptionWhenArgumentsAreNull()
    {
        try
        {
            var reducedSystem = CreateReducedSystem();
            var scriptCreator = new TestScriptCreator();
            using var tempDirectory = new TemporaryDirectory();

            Should.Throw<ArgumentNullException>(() => ExternalSolver.SolveSystemWithExternalProgram(null!, reducedSystem, keepFreeParameters: true, programBinDir: string.Empty, tempDirectory.Path));
            Should.Throw<ArgumentNullException>(() => ExternalSolver.SolveSystemWithExternalProgram(scriptCreator, null!, keepFreeParameters: true, programBinDir: string.Empty, tempDirectory.Path));
            Should.Throw<ArgumentNullException>(() => ExternalSolver.SolveSystemWithExternalProgram(scriptCreator, reducedSystem, keepFreeParameters: true, programBinDir: null!, tempDirectory.Path));
            Should.Throw<ArgumentNullException>(() => ExternalSolver.SolveSystemWithExternalProgram(scriptCreator, reducedSystem, keepFreeParameters: true, programBinDir: string.Empty, path: null!));
        }
        catch (TypeInitializationException)
        {
        }
    }

    [Fact]
    public void ShouldReturnEmptyArrayWhenOutputFileIsNotCreated()
    {
        try
        {
            var reducedSystem = CreateReducedSystem();
            var scriptCreator = new TestScriptCreator();
            using var tempDirectory = new TemporaryDirectory();

            Expression[][] result = ExternalSolver.SolveSystemWithExternalProgram(scriptCreator, reducedSystem, keepFreeParameters: true, programBinDir: string.Empty, tempDirectory.Path);

            result.ShouldBeEmpty();
        }
        catch (TypeInitializationException)
        {
        }
    }

    [Fact]
    public void ShouldReturnNullWhenOutputFileIsEmpty()
    {
        try
        {
            var reducedSystem = CreateReducedSystem();
            var scriptCreator = new TestScriptCreator(createEmptyOutput: true);
            using var tempDirectory = new TemporaryDirectory();

            Expression[][] result = ExternalSolver.SolveSystemWithExternalProgram(scriptCreator, reducedSystem, keepFreeParameters: true, programBinDir: string.Empty, tempDirectory.Path);

            result.ShouldBeNull();
        }
        catch (TypeInitializationException)
        {
        }
    }

    [Fact]
    public void ShouldSetFreeCoefficientsToZeroWhenKeepFreeParametersIsFalse()
    {
        try
        {
            var reducedSystem = CreateReducedSystem();
            var scriptCreator = new TestScriptCreator(["x=x", "//solution"]);
            using var tempDirectory = new TemporaryDirectory();

            Expression[][] result = ExternalSolver.SolveSystemWithExternalProgram(scriptCreator, reducedSystem, keepFreeParameters: false, programBinDir: string.Empty, tempDirectory.Path);

            result.ShouldHaveSingleItem();
            result[0].ShouldHaveSingleItem();
            TensorUtils.Equals(result[0][0], TensorFactory.ParseExpression("A=1")).ShouldBeTrue();
        }
        catch (TypeInitializationException)
        {
        }
    }

    private static ReducedSystem CreateReducedSystem()
    {
        return new ReducedSystem(
            [TensorFactory.ParseExpression("x=0")],
            [TensorFactory.ParseSimple("x")],
            [TensorFactory.ParseExpression("A=x+1")]);
    }

    private sealed class TestScriptCreator(string[]? outputLines = null, bool createEmptyOutput = false)
        : ExternalSolver.ExternalScriptCreator
    {
        private readonly string[] _outputLines = outputLines ?? [];

        public void CreateScript(Expression[] equations, ReducedSystem reducedSystem, string path, bool keepFreeParams)
        {
            string scriptPath = Path.Combine(path, $"equations.{GetScriptExtension()}");
            string outputPath = Path.Combine(path, $"equations.{GetScriptExtension()}Out");
            string escapedOutputPath = outputPath.Replace("'", "''", StringComparison.Ordinal);

            using var writer = new StreamWriter(scriptPath, false);
            if (createEmptyOutput)
            {
                writer.WriteLine($"Set-Content -Path '{escapedOutputPath}' -Value '' -NoNewline");
                return;
            }

            if (_outputLines.Length == 0)
            {
                writer.WriteLine("Write-Output 'No output file is generated by design.'");
                return;
            }

            writer.WriteLine("$lines = @(");
            for (int i = 0; i < _outputLines.Length; i++)
            {
                string escapedLine = _outputLines[i].Replace("'", "''", StringComparison.Ordinal);
                string suffix = i == _outputLines.Length - 1 ? string.Empty : ",";
                writer.WriteLine($"  '{escapedLine}'{suffix}");
            }

            writer.WriteLine(")");
            writer.WriteLine($"Set-Content -Path '{escapedOutputPath}' -Value $lines");
        }

        public string GetScriptExecutionCommand()
        {
            return "pwsh.exe";
        }

        public string GetScriptExtension()
        {
            return "ps1";
        }

        public string[] GetParameters()
        {
            return ["-NoProfile", "-NoLogo", "-File"];
        }
    }

    private sealed class TemporaryDirectory : IDisposable
    {
        public TemporaryDirectory()
        {
            Path = System.IO.Path.Combine(
                System.IO.Path.GetTempPath(),
                "NRedberry.ExternalSolverTests",
                Guid.NewGuid().ToString("N", System.Globalization.CultureInfo.InvariantCulture));
            Directory.CreateDirectory(Path);
        }

        public string Path { get; }

        public void Dispose()
        {
            if (!Directory.Exists(Path))
            {
                return;
            }

            Directory.Delete(Path, recursive: true);
        }
    }
}
